# Bug khi config.js để là 

# // const config = {
# //   development: {
# //     API_BASE_URL: process.env.REACT_APP_API_URL || 'http://localhost:5000'
# //   },
# //   production: {
# //     API_BASE_URL: process.env.REACT_APP_API_URL || 'http://103.253.20.13:5000'
# //   }
# // };

# // export default config[process.env.NODE_ENV || 'development']; 

version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "25037:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
    ports:
      - "25038:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 